### ISSUE TITLE
Practical 3 Task 1.1 Answers

### ISSUE THREAD

**Issue by divyasharma-git** [jreades/i2p#11]
The solution to define avg_tmp in Task 1.1 does not use the input 'temp' in the function itself. 

Proposed solution in workbook:
def avg_tmp(city, temp):
    print(f"The average temperature in {city} is {temperatures[cities.index(city)]}")

city="Edinburgh"
avg_tmp(city, temperatures[cities.index(city)])

However, I think it should be temp within the print function, considering that we are passing the temp index. Otherwise, we don't really need the second input. It should work without it.

So, instead:

def avg_tmp(city, temp):
    print(f"The average temperature in {city} is {temp}")

city="Edinburgh"
avg_tmp(city, temperatures[cities.index(city)])

Warm regards,
Divya

**Comment by jreades** [comment]
Ooooh, I totally missed that. Thanks for flagging!
