### ISSUE TITLE
Error in calculating the centre of the map

### ISSUE THREAD

**Issue by AdamZhou3** [jreades/i2p#15]
`Task 3.4` in `Practical-06`:

`xctr`  should be `-0.1050000...` but not `-0.109999...`

```python
from math import floor, ceil

# Calculate min and max to two decimal points
xmin = floor(pdf['longitude'].min()*100)/100
xmax = ceil(pdf['longitude'].max()*100)/100
ymin = floor(pdf['latitude'].min()*100)/100
ymax = ceil(pdf['latitude'].max()*100)/100

print(xmin, xmax, ymin, ymax) ## -0.5 0.29 51.29 51.69

# Calculate the centre of the map
yctr = (ymax+ymin)/2
xctr = (xmax+xmin)/2  ## xctr = (0.29 + -0.5)/2 = -0.105000...

print(xctr, yctr)  ## -0.10500000000000001 51.489999999999995
```

**Comment by AdamZhou3** [comment]
I noticed another way of doing calculations in the answer.

```python
# Calculate the centre of the map
yctr = ymin+(ymax-ymin)/2
xctr = xmin+(xmax-xmin)/2 

print(xctr)
## -0.10499999999999998
```

It is really strange that a basic operation on finite decimals has an infinite decimal result, and that different operations yield completely different values! I looked into the documentation and found that python has many issues and limitations in performing floating-point arithmetic. For example:

```python
a = 0.29
b = -0.5
(a + b) == -0.21 # False

nums = [1.23e16,-1.23e16, 1 ]
sum(nums) # 0.0  ## but should be 1
```

To perform precise floating-point arithmetic:

```python
from decimal import Decimal
xmax = Decimal("0.29")
xmin = Decimal("-0.5")

xctr = (xmin+xmax)/2 # -0.105
xctr = xmin+(xmax-xmin)/2  # -0.105
```

Sometimes it is both comforting and worrisome to know that powerful computers are so obviously deficient in performing some basic calculations.

Reference: [Floating Point Arithmetic: Issues and Limitations](https://docs.python.org/3/tutorial/floatingpoint.html#representation-error)

**Comment by jreades** [comment]
HI Adam -- I realised that you closed this, but I've actually inserted a 'note' in to the Practical 6 answer on this since it's a great illustration of how things can go subtly wrong if you really need your results to be accurate on output (as opposed to just generally indicating the centre of a map).
