### ISSUE TITLE
SyntaxWarning and the difference between "is not" and "!="

### ISSUE THREAD

**Issue by AdamZhou3** [jreades/i2p#16]
*   get a SyntaxWarning in `practical 07` function `as_markdown`
*   SyntaxWarning: "is not" with a literal. Did you mean "!="?
*   There is a good blog explaining [why python38 syntaxwarning for is literal ](https://adamj.eu/tech/2020/01/21/why-does-python-3-8-syntaxwarning-for-is-literal/)
*   In short, `is` checks for **identity** - if the two variables point to the exact same object. `==` checks for **equality** - if the two variables point at values are equal.

**Comment by jreades** [comment]
Thanks, have fixed this and next commit to GitHub will pick it up.
