### ISSUE TITLE
Incorrect 1D distance formula

### ISSUE THREAD

**Issue by alvova** [jreades/i2p#17]
i2p/lectures/9.1-Data_Space.md
The formula for 1D distance is slightly incorrect, as it could result in negative values. Therefore absolute values should be used. 
Instead of
$$ d(i,j) = (i_{1}-j_{1}) $$
we should use
$$ d(i,j) = |i_{1}-j_{1}| $$

**Comment by jreades** [comment]
Ooooh, good catch! Fixed and will commit soon.
