### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by AdamZh0u** [jreades/i2p#3]
There might be an encoding error (not sure). When I copy the codes on `lectures/3.2-LOLs.md`  lines 130-134:
```python
my_cities = [
  ['London', 51.5072, 0.1275, +0], 
  ['New York', 40.7127, 74.0059, -5], 
  ['Tokyo', 35.6833, 139.6833, +8]
]
```

It raised error:
```
    ['London', 51.5072, 0.1275, +0],
    ^
SyntaxError: invalid character in identifier
```
The same error raised on: 
 `lectures/3.4-Functions.md` lines 63 lines 71-75

Using notepad++ to open these `.md` file will see the difference.

**Comment by jreades** [comment]
Have checked that I can now copy-paste these successfully in the Terminal on Mac. Well-spotted. I'm closing on the assumption that they'll now work on a PC as well but do let me know if not!
