### ISSUE TITLE
Indentation style

### ISSUE THREAD

**Issue by AdamZh0u** [jreades/i2p#4]
I notice that different indentation styles were used in file `lectures/2.3-Python_the_Basics.md`. For example:
Four spaces on lines 225-228
```python
if x < y:
    print("x is less than y")
else:
    print("x is not less than y"
```
and two spaces in other files. 

This may get confusing. By the way, I think an introduction to the indentation style of python will be helpful for beginners.

https://docs.python.org/2.0/ref/indentation.html

**Comment by jreades** [comment]
Yeah, thanks for flagging that one. I'm trying to be consistent about using 2 spaces in the lecture markdown (since it allows me to fit more on each line of code) and tabs in the notebooks (since it's easier) but you're right that I've never really covered this! Let me have a think about it!
