### ISSUE TITLE
radius calculation

### ISSUE THREAD

**Issue by AdamZhou3** [jreades/i2p#5]
`lectures/Practical-02-Foundations_1.ipynb` TOC `3.3 Applying What We've Learned`

 Calculate radius for a sphere of a given volume.

The formula is: 
![](http://latex.codecogs.com/gif.latex?\\(\frac{3}{4}\frac{V}{\pi})^{1/3}=r)

Using the following code, 
```python
v = 14137
r = pow((3*v)/(4*math.pi),1/3)

print(round(r,0)) # result 15.0
```
result is 15 not 11.

**Comment by jreades** [comment]
Thanks for flagging. For some weird reason I had set up the volume at about half that when I was writing the code so I got 11cm as the radius. Bizarre. Must have been thinking about a change for some reason.
