### ISSUE TITLE
urlopen error

### ISSUE THREAD

**Issue by AdamZhou3** [jreades/i2p#6]
`lectures/Practical-03-Foundations_2.ipynb` TOC `Task 3.1. Reading a Remote File`

I ran the following code and got an error  `URLError: <urlopen error [Errno 11004] getaddrinfo failed>`

```python
from urllib.request import urlopen

# Given the info you were given above, what do you 
# think the value of 'url' should be? What
# type of variable is it? int or string? 
url = 'https://github.com/jreades/i2p/raw/master/data/2020-08-24-sample-listings-simple.csv'

# Read the URL stream into variable called 'response'
# using the function that we imported above
response = urlopen(url)

# Now read from the stream, decoding so that we get actual text
datafile = response.read().decode('utf-8')

# You might want to explore what `__class__` and `__name__`
# offer, but basically the give us a way of finding out what
# is 'behind' more complex variables
print("datafile variable is of type: '" + datafile.__class__.__name__ + "'.\n")
```

It seems to be a proxy error as described [here](https://stackoverflow.com/questions/7334199/getaddrinfo-failed-what-does-that-mean).

I tried to use different url `url = "https://raw.githubusercontent.com/jreades/i2p/master/data/2020-08-24-sample-listings-simple.csv`, but it failed.

**Comment by AdamZhou3** [comment]
Set the proxy environment variable refering to the answer [here](https://stackoverflow.com/a/28153935) fixed this problem.

```python
import os
os.environ['HTTP_PROXY'] = 'http://127.0.0.1:10809'
os.environ['HTTPS_PROXY'] = 'http://127.0.0.1:10809'
```

**Comment by jreades** [comment]
Again, thanks for flagging this -- I've inserted a note into practical 3 in case people have this issue next year!
